name: "Deploy to GitHub Pages"

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
    build:
        name: Build and Upload Site
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            node-version: [20]
        steps:
          - uses: actions/checkout@v4
          - name: Install pnpm
            uses: pnpm/action-setup@v4
            with:
                version: 9
          - name: Install Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'
          - name: Install Dependencies
            run: pnpm install
          - name: Vite Build
            run: pnpm run build
          - name: Upload Artifact
            id: deployment           
            uses: actions/upload-pages-artifact@v3
            with:
              path: dist/
              
    deploy:
        name: Deploy Site
        runs-on: ubuntu-latest
        needs: build
        permissions:
          pages: write
          id-token: write
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
